name: "Dependency Review"
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: before
        if: always()
        uses: actions/dependency-review-action@v4.3.3
        with:
          allow-licenses: (Apache-2.0 OR MIT)
          fail-on-severity: critical
      - name: after
        if: always()
        uses: actions/dependency-review-action@v4.3.4
        with:
          allow-licenses: (Apache-2.0 OR MIT)
          fail-on-severity: critical